spring:
  redis:
    host: 192.168.121.129
  cloud:
    gateway:
      routes:
        # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
        - id: test
          # 匹配后提供服务的路由地址
          uri: http://192.168.100.82:8206/
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/EstateSupervise/**
          filters:
